test_that("arrow archive functions ok", {
  skip_if_not_installed("arrow")
  cloud <- ichimoku(sample_ohlc_data)
  filename <- tempfile()
  archive(cloud, filename)
  restored <- archive(filename)
  unlink(filename)
  expect_identical(restored, cloud)
  expect_error(archive(), "is used to")
  expect_error(archive(cloud, cloud, cloud), "Too many arguments")
  expect_error(archive(cloud), "supplied as a string")
  expect_error(archive(cloud, cloud), "supplied as a string")
  expect_error(archive(object = sample_ohlc_data, filename = filename), "only writes ichimoku")
  arrow::write_feather(sample_ohlc_data, filename)
  expect_error(archive(filename = filename), "not an archived ichimoku")
  expect_error(archive(object = cloud), "specified without")
})
