test_that("archive functions ok", {
  skip_if_not_installed("arrow")
  skip_if_not_installed("openssl")
  cloud <- ichimoku(sample_ohlc_data)
  df <- xts_df(cloud, preserve.attrs = TRUE)
  archive(cloud, filename <- tempfile())
  restored <- archive(filename)
  unlink(filename)
  expect_identical(restored, cloud)
  expect_error(archive(), "is used to")
  expect_error(archive(cloud, cloud, cloud), "Too many arguments")
  expect_error(archive(cloud), "supplied as a string")
  expect_error(archive(cloud, cloud), "supplied as a string")
  expect_error(archive(object = cloud), "specified without")
  filename <- tempfile()
  archive(object = sample_ohlc_data, filename = filename)
  sample1 <- archive(filename = filename)
  unlink(filename)
  expect_identical(sample_ohlc_data, sample1)
  dg <- structure(df, ichimoku351 = TRUE)
  arrow::write_feather(dg, filename <- tempfile())
  expect_message(archive(filename), "cannot be verified")
  unlink(filename)
  dh <- structure(df, ichimoku351 = TRUE, sha256351 = "010101010101")
  arrow::write_feather(dh, filename <- tempfile())
  expect_warning(archive(filename), "does not match the original")
  unlink(filename)
})
