test_that("arrow archive functions ok", {
  skip_if_not_installed("arrow")
  cloud <- ichimoku(sample_ohlc_data)
  filename <- tempfile()
  ichimoku_write(cloud, filename)
  restored <- ichimoku_read(filename)
  expect_equal(restored, cloud, ignore_attr = TRUE)
  expect_error(ichimoku_write(), "No object specified")
  expect_error(ichimoku_write(cloud), "must be specified")
  expect_error(ichimoku_write(sample_ohlc_data, filename), "ichimoku objects")
  expect_error(ichimoku_read(), "No file specified")
  arrow::write_feather(sample_ohlc_data, filename)
  expect_error(ichimoku_read(filename), "only ichimoku objects")
  unlink(filename)
})
