test_that("arrow archive functions ok", {
  skip_if_not_installed("arrow")
  cloud <- ichimoku(sample_ohlc_data)
  filename <- tempfile()
  archive(cloud, filename)
  restored <- archive(filename)
  expect_equal(restored, cloud, ignore_attr = TRUE)
  expect_error(archive(), "is used to")
  expect_error(archive(cloud), "supplied as a string")
  expect_error(archive(cloud, cloud), "supplied as a string")
  expect_error(archive(sample_ohlc_data, filename), "only writes ichimoku")
  arrow::write_feather(sample_ohlc_data, filename)
  expect_error(archive(filename), "not an archived ichimoku")
  unlink(filename)
})
