// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef RCPP_ichimoku_RCPPEXPORTS_H_GEN_
#define RCPP_ichimoku_RCPPEXPORTS_H_GEN_

#include <Rcpp.h>

namespace ichimoku {

    using namespace Rcpp;

    namespace {
        void validateSignature(const char* sig) {
            Rcpp::Function require = Rcpp::Environment::base_env()["require"];
            require("ichimoku", Rcpp::Named("quietly") = true);
            typedef int(*Ptr_validate)(const char*);
            static Ptr_validate p_validate = (Ptr_validate)
                R_GetCCallable("ichimoku", "_ichimoku_RcppExport_validate");
            if (!p_validate(sig)) {
                throw Rcpp::function_not_exported(
                    "C++ function with signature '" + std::string(sig) + "' not found in ichimoku");
            }
        }
    }

    inline NumericVector maxOver(const SEXP& x, int window) {
        typedef SEXP(*Ptr_maxOver)(SEXP,SEXP);
        static Ptr_maxOver p_maxOver = NULL;
        if (p_maxOver == NULL) {
            validateSignature("NumericVector(*maxOver)(const SEXP&,int)");
            p_maxOver = (Ptr_maxOver)R_GetCCallable("ichimoku", "_ichimoku_maxOver");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_maxOver(Shield<SEXP>(Rcpp::wrap(x)), Shield<SEXP>(Rcpp::wrap(window)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<NumericVector >(rcpp_result_gen);
    }

    inline NumericVector minOver(const SEXP& x, int window) {
        typedef SEXP(*Ptr_minOver)(SEXP,SEXP);
        static Ptr_minOver p_minOver = NULL;
        if (p_minOver == NULL) {
            validateSignature("NumericVector(*minOver)(const SEXP&,int)");
            p_minOver = (Ptr_minOver)R_GetCCallable("ichimoku", "_ichimoku_minOver");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_minOver(Shield<SEXP>(Rcpp::wrap(x)), Shield<SEXP>(Rcpp::wrap(window)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<NumericVector >(rcpp_result_gen);
    }

}

#endif // RCPP_ichimoku_RCPPEXPORTS_H_GEN_
