// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// maxOver
NumericVector maxOver(const SEXP& x, int window);
RcppExport SEXP _ichimoku_maxOver(SEXP xSEXP, SEXP windowSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const SEXP& >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    rcpp_result_gen = Rcpp::wrap(maxOver(x, window));
    return rcpp_result_gen;
END_RCPP
}
// minOver
NumericVector minOver(const SEXP& x, int window);
RcppExport SEXP _ichimoku_minOver(SEXP xSEXP, SEXP windowSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const SEXP& >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    rcpp_result_gen = Rcpp::wrap(minOver(x, window));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ichimoku_maxOver", (DL_FUNC) &_ichimoku_maxOver, 2},
    {"_ichimoku_minOver", (DL_FUNC) &_ichimoku_minOver, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_ichimoku(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
