# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Maximum over a rolling window
#'
#' Calculate the maximum over a rolling window
#'
#' @param x a vector.
#' @param window size of the rolling window.
#' @return A vector of the same length as 'x' with elements 1 to
#'     (length(window) - 1) containing NAs.
#' @examples
#' max <- maxOver(sample_ohlc_data$Close, 9L)
#' @export
maxOver <- function(x, window) {
    .Call(`_ichimoku_maxOver`, x, window)
}

#' Minimum over a rolling window
#'
#' Calculate the minimum over a rolling window
#'
#' @param x a vector.
#' @param window size of the rolling window.
#' @return A vector of the same length as 'x' with elements 1 to
#'     (length(window) - 1) containing NAs.
#' @examples
#' min <- minOver(sample_ohlc_data$Close, 9L)
#' @export
minOver <- function(x, window) {
    .Call(`_ichimoku_minOver`, x, window)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_ichimoku_RcppExport_registerCCallable', PACKAGE = 'ichimoku')
})
